version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: helpdesk-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - helpdesk-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  # MAILPIT - FAKE SMTP SERVER
  mailpit:
    image: axllent/mailpit
    container_name: helpdesk-mailpit
    restart: always
    ports:
      - "8025:8025" #UI przegladarka do testow
      - "1025:1025" #port SMTP dla aplikacji

    networks:
      - helpdesk-network
  # MinIO - S3 compatible storage
  minio:
    image: minio/minio
    container_name: helpdesk-minio
    ports:
      - "9000:9000" #API
      - "9001:9001" # Console UI
    environment:
      - MINIO_ROOT_USER: admin
      - MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    networks:
      - helpdesk-network
    volumes:
      -minio-data:/data

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: helpdesk-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      - helpdesk-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: src/AuthService/Dockerfile
    container_name: helpdesk-auth
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${AUTH_DB_CONNECTION}
      JwtSettings__SecretKey: ${JWT_SECRET}
      JwtSettings__Issuer: ${JWT_ISSUER}
      JwtSettings__Audience: ${JWT_AUDIENCE}
      JwtSettings__ExpirationMinutes: ${JWT_EXPIRATION_MINUTES}
      JwtSettings__RefreshTokenExpirationDays: ${JWT_REFRESH_TOKEN_EXPIRATION_DAYS}
      MessagingSettings__ExchangeName: helpdesk-events
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - helpdesk-network

  # Ticket Service
  ticket-service:
    build:
      context: .
      dockerfile: src/TicketService/Dockerfile
    container_name: helpdesk-tickets
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${TICKET_DB_CONNECTION}
      MessagingSettings__HostName: ${RABBITMQ_HOST}
      MessagingSettings__UserName: ${RABBITMQ_USER}
      MessagingSettings__Password: ${RABBITMQ_PASSWORD}
      MessagingSettings__ExchangeName: ${RABBITMQ_EXCHANGE}
      JwtSettings__SecretKey: ${JWT_SECRET}
      JwtSettings__Issuer: ${JWT_ISSUER}
      JwtSettings__Audience: ${JWT_AUDIENCE}
      FileStorage__ServiceUrl: http://minio:9000
      FileStorage__AccessKey: admin
      FielStorage__SecretKey: password123
      FileStorage__BucketName: helpdesk-attachments
    ports:
      - "${TICKET_SERVICE_PORT}:8080"
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - helpdesk-network

  # User Service
  user-service:
    build:
      context: .
      dockerfile: src/UserService/Dockerfile
    container_name: helpdesk-users
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${USER_DB_CONNECTION}
      MessagingSettings__HostName: ${RABBITMQ_HOST}
      MessagingSettings__UserName: ${RABBITMQ_USER}
      MessagingSettings__Password: ${RABBITMQ_PASSWORD}
      MessagingSettings__ExchangeName: helpdesk-events
      JwtSettings__SecretKey: ${JWT_SECRET}
      JwtSettings__Issuer: ${JWT_ISSUER}
      JwtSettings__Audience: ${JWT_AUDIENCE}
    ports:
      - "${USER_SERVICE_PORT}:8080"
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - helpdesk-network

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    container_name: helpdesk-notifications
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MessagingSettings__HostName: helpdesk-rabbitmq
      MessagingSettings__UserName: ${RABBITMQ_USER}
      MessagingSettings__Password: ${RABBITMQ_PASSWORD}
      MessagingSettings__ExchangeName: helpdesk-events
      EmailSettings__SmtpServer: mailpit
      EmailSettings__SmtpPort: 1025
      EmailSettings__SenderEmail: noreply@helpdesk.com
      EmailSettings__SenderName: "Helpdesk System"
      EmailSettings__SmtpPassword: ""
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:8080"
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      mailpit:
        condition: service_started
    networks:
      - helpdesk-network

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    container_name: helpdesk-gateway
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "${API_GATEWAY_PORT}:8080"
    depends_on:
      auth-service:
        condition: service_started
      ticket-service:
        condition: service_started
      user-service:
        condition: service_started
    networks:
      - helpdesk-network

volumes:
  postgres-data:
  minio-data:

networks:
  helpdesk-network:
    driver: bridge

